### PR TITLE
Lesson 7

### PR DESCRIPTION
**Pull request by lolitamalinovskaya**

### CODE REVIEW

**Comment by romos21** [comment]
@lolitamalinovskaya remove width 100% and max-width for sections cause of this problem becomes [
image
](url)

**Comment by romos21** [comment]
image
change styles of this

**Comment by romos21** [comment]
@lolitamalinovskaya use line with change display (none <-> block) depends on hover on navbar element and set position absolute to the line with a bottom value less than 0 - for example : bottom: -35px
image

**Comment by lolitamalinovskaya** [comment]
Please, look at my last commit. I removed max-width and width 100% in the sections, fixed mistakes in properties of the top_section and increased the distance from the nav bar to the line

**Comment by romos21** [comment]
@lolitamalinovskaya merged it!

**Pull request merged**
